name: BuildAndPublishNuget

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Build
      run: msbuild
    - name: Publish
      uses: brandedoutcast/publish-nuget@v2.5.2  
      with: 
        PROJECT_FILE_PATH: uplink.NET.UnoHelpers/uplink.NET.UnoHelpers.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        INCLUDE_SYMBOLS: true
