name: BuildAndPublishNuget

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Restore NuGet Packages
      run: nuget restore
    - name: Build
      run: msbuild /p:Configuration=Nuget /t:Rebuild /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg
    - name: Nuget Push Helpers
      run: nuget push D:\a\uplink.NET.UnoHelpers\uplink.NET.UnoHelpers\uplink.NET.UnoHelpers\bin\Nuget\uplink.NET.UnoHelpers.0.9.31.nupkg -ApiKey ${{secrets.NUGET_API_KEY}} -Source https://api.nuget.org/v3/index.json
    - name: Nuget Push Contracts
      run: nuget push D:\a\uplink.NET.UnoHelpers\uplink.NET.UnoHelpers\uplink.NET.UnoHelpers.Contracts\bin\Nuget\uplink.NET.UnoHelpers.Contracts.0.9.31.nupkg -ApiKey ${{secrets.NUGET_API_KEY}} -Source https://api.nuget.org/v3/index.json
